# Generated by Django 4.2.4 on 2023-08-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailSettings',
            new_name='MailingSettings',
        ),
    ]
