# Generated by Django 4.2.4 on 2023-08-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingsettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mail_service_response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ почтового сервиса'),
        ),
    ]
